export class Concesionario {
    id: number;
    nombre: string;
    telefono: string;
    direccion: string;
    provincia: string;
    localidad: string;
    codigopostal: string;
    telefonoTaller: string;
    responsableTaller: string;
    telefonoResTaller: string;
    jefePostVenta: string;
    telefonoJefePostVenta: string;
    emailResponsableTaller: string;
    emailJefePostVenta: string;
    emailSsangyongCorp: string;
    nombreGerente: string;
    telefonoGerente: string;
    emailGerente: string;
    numDSM: string;
    numMSM: string;
    clavesSIW: string;
    responsableRecambios: string;
    emailRecambios: string;
    emailAttCliente: string;
    moGarantias: string;
    moClient: string;
    otrasMarcas: string;
}
